const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages=[['overview','⌂','总览','总览 / 应急总控台','在线仿真 · 态势分析 · 快速决策 · 协同处置'],['data','▦','数据中心','数据中心 / 多源数据与态势感知','汇聚监测数据，完成校验、去重、入库与状态更新'],['prediction','◉','风险预测','风险预测 / 预警分析','基于时间序列预测与可解释风险指数，连接风险研判和资源前置'],['dispatch','▣','资源调度','资源调度 / 协同处置','多资源协同 · 60 分钟滚动窗口 · 执行锁定 · 稳定重规划'],['strategy','◈','策略决策','策略决策 / 决策推演','灾情理解、预案检索与方案对比，人工确认后进入执行'],['replay','◷','事件复盘','事件复盘 / 运行与实验中心','从数据库恢复历史快照，追踪每次状态变化和调度决策']];
let state,page='overview',maps=[],charts=[],pending=null,forecastModel='AR',forecastStation='S01',history=[];
async function api(url,body){const r=await fetch('/api/'+url,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',5000)}
async function action(fn){const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();await refresh();}catch(e){toast(e.message)}finally{buttons.forEach(b=>b.disabled=false)}}
function panel(title,body,extra='',cls=''){return `<section class="panel ${cls}"><div class="panel-title"><span>${title}</span><small>${extra}</small></div>${body}</section>`}
function table(headers,rows){return `<div class="wide-table"><table class="rows"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function badge(text,type=''){return `<span class="badge ${type}">${esc(text)}</span>`}
function metric(icon,label,value,unit,sub,color=''){return `<div class="metric"><div class="symbol ${color}">${icon}</div><div><label>${label}</label><strong class="${color}">${value}</strong> <em>${unit}</em><small>${sub}</small></div></div>`}
function cards(mode='overview'){let m=state.metrics,f=state.forecast;if(mode==='data')return `<div class="cards">${metric('▦','监测数据类型',Object.keys(state.sensor_types).length,'类',state.environment_mode==='historical'?'降雨 / 土壤':'气象 / 水文 / 土壤 / 位移')}${metric('⌁','监测站点',3,'处',state.environment_mode==='historical'?'产品网格采样点':'模拟观测站')}${metric('▥','当前可见观测',m.observations,'条','按模拟时刻过滤')}${metric('✓','存储状态','SQLite','','事务持久化','green')}${metric('◷','状态版本',state.revision,'','每次变更保留快照')}${metric('◈','数据表',state.database.tables.length,'张','统一后台状态')}</div>`;
if(mode==='dispatch')return `<div class="cards">${metric('♟','可用救援资源',m.available,'项',`共 ${m.total} 项`)}${metric('➤','已锁定资源',m.busy,'项','在途 / 作业 / 协同预留')}${metric('▤','待分配任务',m.pending,'项','已公开且尚未锁定')}${metric('✓','已完成任务',m.completed,'项','执行器实际完成','green')}${metric('◷','规划窗口',state.settings.horizon,'分钟','连续任务序列')}${metric('⇄','道路通行率',Math.round((m.roads-m.blocked)/m.roads*100),'%',`${m.blocked} 条道路阻断`)}</div>`;
return `<div class="cards">${metric('☁','累计降雨量',m.rainfall,'mm','过去24小时 · 当前环境 S01')}${metric('!','综合风险指数',f.score.toFixed(2),'',f.level+' · 非灾害概率','orange')}${metric('♟','场景覆盖人口',m.affected_population.toLocaleString(),'人','模拟村落人口')}${metric('♡','报告失联人数',m.missing,'人','来自人工确认事件','red')}${metric('✚','可用救援资源',m.available,'项',`共 ${m.total} 项异构资源`)}${metric('⇄','道路运行状态',m.blocked,'条中断',`共 ${m.roads} 条模拟道路`,m.blocked?'red':'green')}</div>`}
function tasks(limit=6){return state.tasks.slice().sort((a,b)=>a.priority-b.priority).slice(0,limit).map(t=>`<div class="task"><span class="priority p${t.priority}">P${t.priority}</span><div><strong>${esc(t.name)}</strong><p>${esc(node(t.node).name)} · 第 ${t.deadline} 分钟前</p><p>${Object.entries(t.requirements).map(([k,v])=>`${esc(state.resource_names[k])} ×${v}`).join(' · ')}</p></div>${badge(statusName(t.status),t.status==='completed'?'good':t.status==='pending'?'warn':'')}</div>`).join('')||'<div class="empty">暂无任务</div>'}
function node(id){return state.nodes.find(n=>n.id===id)||{name:id,lat:30.08,lon:102.18}}
function statusName(s){return ({pending:'待分配',committed:'执行中',completed:'已完成',idle:'可用',travel:'行进中',working:'作业中',reserved:'协同预留',failed:'故障不可用'})[s]||s}
function events(limit=6){return state.events.slice(-limit).reverse().map(e=>`<div class="timeline-item"><time>${String(Math.floor(e.minute/60)+9).padStart(2,'0')}:${String(e.minute%60).padStart(2,'0')}</time><span class="dot"></span><p>${esc(e.text)}</p></div>`).join('')}
function mapPanel(id='main-map',title='康定地区 · 应急态势与资源地图'){return `<section class="panel"><div id="${id}" class="map"><div class="map-title">${title}<small>${state.time} · ${state.forecast.level}</small></div><div class="map-legend">🔴 高风险研究区域<br>🔵 模拟救援资源　✚ 医疗点<br>━ 可通行道路　┄ 阻断道路<br>◉ ${state.routing_mode==='osm'?'OSM道路 / 模拟资源':'模拟节点与路线'}</div></div><div class="map-note">© OpenStreetMap contributors · ${state.routing_mode==='osm'?'ODbL 道路快照寻路，模拟任务与速度':'模拟点位与路网，非真实救援路线'}</div></section>`}
function mapRender(id='main-map',risk=false){let el=document.getElementById(id);if(!el)return;const map=L.map(id,{zoomControl:false}).setView([30.075,102.179],11);maps.push(map);L.control.zoom({position:'bottomright'}).addTo(map);const tile=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);let failed=0;tile.on('tileerror',()=>{failed++;if(failed===3){const note=el.nextElementSibling;note.textContent='底图网络不可用；模拟经纬度、风险区、道路和资源图层仍可交互';}});
const bounds=state.nodes.filter(n=>n.kind!=='road').map(n=>[n.lat,n.lon]);map.fitBounds(bounds,{padding:[35,45]});
for(const n of state.nodes){if(n.kind==='road')continue;if(['N4','N8','N5'].includes(n.id)){L.circle([n.lat,n.lon],{radius:1400+(state.forecast.zones?.find(z=>z.node===n.id)?.score??state.forecast.score)*1400,color:(state.forecast.zones?.find(z=>z.node===n.id)?.score??state.forecast.score)>.7?'#f2595a':'#f5a623',weight:1,fillOpacity:risk?.3:.13}).addTo(map)}let color=n.kind==='hospital'?'#f35a6c':n.kind==='shelter'?'#0bb594':'#2185f6';L.circleMarker([n.lat,n.lon],{radius:7,color:'white',weight:2,fillColor:color,fillOpacity:1}).addTo(map).bindTooltip(esc(n.name),{permanent:true,direction:'top',className:'node-label',offset:[0,-8]}).bindPopup(`<b>${esc(n.name)}</b><br>模拟节点 ${n.id}<br>场景人口 ${n.population}`)}
for(const road of state.roads){const a=node(road.u),b=node(road.v);L.polyline(road.geometry||[[a.lat,a.lon],[b.lat,b.lon]],{color:road.blocked?'#f14e5b':'#e8a43e',weight:road.blocked?5:2.5,dashArray:road.blocked?'8,7':null}).addTo(map).bindPopup(`${road.id} · ${road.directed?'有向路段 / 估算':'模拟行程'} ${road.minutes} 分钟<br>${road.blocked?'道路阻断':'道路可通行'}`)}
const colors={rescue_team:'#2583ff',medical_team:'#f45d70',ambulance:'#d54fd2',engineering_team:'#06b78e',excavator:'#069b78',drone:'#8a63da',supply_vehicle:'#f6a22d'};
for(const a of displayAssignments()){L.polyline(a.geometry?.length?a.geometry:a.path.map(id=>[node(id).lat,node(id).lon]),{color:colors[a.type],weight:3,opacity:.7,dashArray:'5,5'}).addTo(map).bindPopup(`${esc(a.resource)} → ${esc(a.name)}<br>出发 ${a.depart} · 开始 ${a.start} · 完成 ${a.end}`)}
for(const r of state.resources){const n=node(r.node);L.circleMarker([n.lat+(r.id.charCodeAt(0)%4)*.001,n.lon+(Number(r.id.slice(-2))%4)*.001],{radius:4,color:colors[r.type],fillOpacity:1}).addTo(map).bindPopup(`${esc(r.name)} · ${esc(statusName(r.status))}`)}return map;}
function chart(id,options){const el=document.getElementById(id);if(!el)return;const c=echarts.init(el);charts.push(c);c.setOption({textStyle:{fontFamily:'Microsoft YaHei',color:'#71849b'},grid:{left:40,right:18,top:25,bottom:30},tooltip:{trigger:'axis'},...options});}
function line(id,history,forecast=[],unit=''){chart(id,{xAxis:{type:'category',boundaryGap:false,data:[...history,...forecast].map(p=>p.minute+'分'),axisLabel:{fontSize:9}},yAxis:{type:'value',name:unit,splitLine:{lineStyle:{color:'#edf2f7'}}},series:[{name:'观测值',type:'line',data:[...history.map(p=>p.value),...forecast.map(()=>null)],symbol:'none',smooth:true,itemStyle:{color:'#2089ff'},areaStyle:{color:'#2089ff',opacity:.12}},{name:'预测值',type:'line',data:[...history.map(()=>null),...forecast.map(p=>p.value)],symbol:'none',lineStyle:{type:'dashed'},itemStyle:{color:'#f59c28'}}]})}
function utilization(){return Object.entries(state.resource_names).map(([kind,name])=>{let all=state.resources.filter(r=>r.type===kind),busy=all.filter(r=>r.active).length;return `<div class="progress-row"><span>${name}</span><span class="bar"><i style="width:${busy/all.length*100}%"></i></span><span>${busy} / ${all.length}</span></div>`}).join('')}
function renderOverview(){const f=state.forecast;$('#content').innerHTML=cards()+`<div class="layout"><div class="stack">${panel(state.environment_mode==='historical'?'历史产品观测':'模拟在线监测',`<div class="panel-body">${table(['监测类型','当前值','状态'],Object.entries(f.series).map(([k,v])=>[state.sensor_types[k].label,v.history.at(-1).value.toFixed(1)+' '+v.unit,badge('有效','good')]))}</div>`,'S01')}${panel('事件动态',`<div class="panel-body">${events()}</div>`,'数据库事件流')}</div><div>${mapPanel()}<div class="bottom-grid">${panel('降雨趋势','<div class="chart" id="rain-chart"></div>','近期观测')}${panel('资源使用情况',`<div class="panel-body">${utilization()}</div>`)}${panel('风险指数趋势','<div class="chart" id="risk-chart"></div>',`未来${12*(state.forecast.cadence_minutes||5)}分钟`)}</div></div><div class="stack">${panel('当前任务',`<div class="panel-body">${tasks(5)}</div>`,`${state.tasks.length} 项`)}${panel('应急决策提示',`<div class="panel-body"><div class="notice">${f.score>=.7?'风险指数较高，可在滚动计划中启用搜救队与无人机前置。':'持续关注监测变化，按任务需求组织资源。'}<br>当前 ${state.metrics.pending} 项任务等待分配，${state.metrics.blocked} 条道路中断。<br>已锁定的协同任务会保留执行承诺。</div><button class="primary small full" onclick="navigate('dispatch')">查看调度计划 →</button></div>`,'基于当前状态')}</div></div>`;mapRender();line('rain-chart',f.series.rainfall.history,[],'mm/h');line('risk-chart',[],f.risk.map(r=>({minute:r.minute,value:r.score})),'指数');}
function renderData(){const latest=Object.keys(state.sensor_types).map(k=>[state.sensor_types[k].label,badge('已接入','good'),state.environment_mode==='historical'?'核验 JSON':'CSV / SQLite',state.environment_mode==='historical'?'3 个采样点':'3 个站点']);$('#content').innerHTML=cards('data')+`<div class="layout"><div class="stack">${panel('数据源列表',`<div class="panel-body">${table(['名称','状态','接口','站点'],latest)}<p class="notice full">当前环境的可用变量按观测时钟进入页面；历史产品仅用于事后回放。</p></div>`)}${panel('新增数据接入',`<div class="panel-body"><p style="font-size:12px;color:#8295aa">模拟环境可导入观测 JSON，校验数值、单位、坐标及重复记录。历史环境使用已核验文件，禁止混合导入。</p><input type="file" id="import-file" accept=".json"><button id="import-btn" class="primary full">校验并入库</button><div id="import-result"></div></div>`)}</div><div>${mapPanel('data-map','多源监测站与风险分布')}${panel('数据处理流水线',`<div class="flow">${['数据接入','字段校验','去重存储','状态更新','预测计算'].map((v,i)=>`<div><b>${i+1}</b><small>${v}</small></div>`).join('')}</div>`,'观测校验 / 文件与快照持久化','full')}</div><div class="stack">${panel('数据质量概览',`<div class="panel-body"><div class="notice">已存储观测通过值域和单位校验。无效输入会返回逐行错误，不写入观测表。</div>${['可用变量字段','唯一键去重','观测时间过滤','经纬度范围','来源标签保留'].map(v=>`<div class="check"><span class="green">✓</span>${v}</div>`).join('')}</div>`)}${panel('数据库结构',`<div class="panel-body">${state.database.tables.map(t=>`<div class="check"><span class="blue">▤</span>${esc(t)}</div>`).join('')}</div>`,state.database.file)}</div></div>${panel('当前时点数据消息流',`<div class="panel-body scroll">${table(['时间','站点','监测类型','数值','单位','质量','来源'],state.observations.slice(-30).reverse().map(o=>[o.timestamp.slice(11,16),esc(o.station_id),state.sensor_types[o.type].label,o.value,esc(o.unit),badge(o.quality,'good'),esc(o.provenance)]))}</div>`,'最新30条','full')}`;mapRender('data-map');$('#import-btn').onclick=()=>action(async()=>{let file=$('#import-file').files[0];if(!file)throw Error('请先选择 JSON 文件');let rows=JSON.parse(await file.text());const r=await api('ingest',{rows});toast(`已接收 ${r.accepted}，重复 ${r.duplicates}，拒绝 ${r.rejected}`);if(r.errors.length){$('#modal-content').innerHTML='<h3>数据校验结果</h3><pre>'+esc(JSON.stringify(r,null,2))+'</pre>';$('#modal').showModal()}})}
async function renderPrediction(){
 const f=forecastModel==='AR'?state.forecast:await api('forecast?model='+encodeURIComponent(forecastModel));
 const stationSeries=Object.fromEntries(Object.entries(f.station_series).filter(([k])=>k.startsWith(forecastStation+':')).map(([k,v])=>[k.split(':')[1],v]));
 $('#content').innerHTML=`<div class="toolbar"><label>查看站点 / 采样点</label><select id="forecast-station">${['S01','S02','S03'].map(s=>`<option ${s===forecastStation?'selected':''}>${s}</option>`).join('')}</select>${['Persistence','AR','Gradient Boosting'].map(m=>`<button class="${m===forecastModel?'selected':''}" data-model="${m}">${m}</button>`).join('')}<span class="badge warn">${f.environment_mode==='historical'?'真实历史 · 小时尺度':'模拟 · 5分钟尺度'} / 风险不是概率</span></div><p class="notice">三个站点的全部可用变量联合输入；下方切换仅用于查看各站预测。当前决策使用 AR 模型，其他模型供诊断对照。${f.environment_mode==='historical'?'最终产品和再分析包含事后信息，不代表当时可获得的现场数据。':''}</p><div class="layout"><div class="stack">${Object.entries(stationSeries).map(([k,v])=>panel(forecastStation+' · '+state.sensor_types[k].label,`<div class="chart" id="pred-${k}"></div>`,v.unit)).join('')}</div><div>${mapPanel('forecast-map','区域风险与候选前置点')}${panel(`未来${12*f.cadence_minutes}分钟风险排序`,'<div class="chart large" id="forecast-risk"></div>',f.risk_mode==='empirical'?'历史经验分位':'规则归一化','full')}</div><div class="stack">${panel('各区域预测权重',`<div class="panel-body">${table(['采样点','候选区域','预测权重'],f.zones.map(z=>[z.station_id,z.node,z.score.toFixed(2)]))}<p class="notice">采样点与候选区域的对应关系为人工实验映射，三处网格样本不是现场监测站。</p></div>`)}${panel('S01 首步风险分项',`<div class="panel-body">${f.components.map(c=>`<div class="progress-row"><span>${c.name}</span><span class="bar"><i style="width:${c.contribution*100}%;background:#fa9750"></i></span><span>${c.contribution.toFixed(2)}</span></div>`).join('')}<p class="notice">可用变量权重归一化。总体风险为各区域未来窗口的最大值，不等于S01首步分项之和。</p></div>`)}${panel('预测与前置联动',`<div class="panel-body"><div class="notice warn">比较三个候选区域及低 / 中 / 高实验情景；高情景包含新增紧急需求权重和道路中断。前置仅移动剩余资源，不把预测写成真实灾情。</div><button class="primary full" onclick="navigate('dispatch')">查看调度与决策追踪</button></div>`)}${panel('验证数据范围',`<div class="panel-body"><p class="notice">历史训练 / 留出验证均早于场景第0分钟；固定训练段评估递归预测，在线模型再用全部场景前历史拟合。误差按站点、变量、原生时距分别报告。</p></div>`)}</div></div>`;
 mapRender('forecast-map',true);for(const [k,v] of Object.entries(stationSeries))line('pred-'+k,v.history.slice(-18),v.forecast,v.unit);
 line('forecast-risk',[],f.risk.map(r=>({minute:r.minute,value:r.score})),'指数');
 $('#forecast-station').onchange=()=>{forecastStation=$('#forecast-station').value;render()};
 document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{forecastModel=b.dataset.model;render()});
}
function gantt(id){const a=displayAssignments();if(!a.length){$('#'+id).innerHTML='<div class="empty">生成滚动计划后显示多任务资源时间轴</div>';return}const resources=[...new Set(a.map(x=>x.resource))];chart(id,{grid:{left:85,right:25,top:20,bottom:35},tooltip:{formatter:p=>{let a=p.data.raw;return `${esc(a.resource)} → ${esc(a.name)}<br>出发 ${a.depart} / 开始 ${a.start} / 结束 ${a.end}`}},xAxis:{type:'value',min:state.minute,name:'模拟分钟'},yAxis:{type:'category',data:resources,axisLabel:{fontSize:9}},series:[{type:'custom',renderItem:(params,api)=>{const y=api.value(0),start=api.coord([api.value(1),y]),end=api.coord([api.value(2),y]);return {type:'rect',shape:{x:start[0],y:start[1]-5,width:Math.max(1,end[0]-start[0]),height:10,r:3},style:api.style()};},encode:{x:[1,2],y:0},data:a.flatMap(x=>[{value:[resources.indexOf(x.resource),x.depart,x.arrival],raw:x,itemStyle:{color:'#f3b24c'}},{value:[resources.indexOf(x.resource),x.start,x.end],raw:x,itemStyle:{color:x.provisional?'#b398e8':'#4794f6'}}]).filter(x=>x.value[2]>x.value[1])}]})}
function renderDispatch(){let a=displayAssignments();$('#content').innerHTML=cards('dispatch')+`<div class="layout"><div class="stack">${panel('待分配与执行任务',`<div class="panel-body scroll" style="max-height:530px">${tasks(20)}</div>`)}${panel('滚动优化策略',`<div class="panel-body"><div class="field"><label>规划窗口（分钟）</label><select id="horizon">${[30,60,90,120].map(n=>`<option ${n===state.settings.horizon?'selected':''}>${n}</option>`).join('')}</select></div><div class="field"><label>方案变化惩罚</label><input id="stability" type="number" min="0" max="200" value="${state.settings.stability}"></div><label class="check"><input id="preposition" type="checkbox" ${state.settings.forecast?'checked':''}>启用预测资源前置</label><button id="optimize" class="primary">重新优化</button><p class="notice full">任务要求全部资源同步开始；每项资源可在窗口内连续执行多个任务。只锁定到达执行时刻的任务。</p></div>`)}</div><div>${mapPanel('dispatch-map','灾害态势与资源调度地图')}${panel('资源执行时间轴 · 橙色行程 / 蓝色作业 / 紫色前置','<div id="gantt" class="gantt"></div>',state.plan.status||'未求解','full')}</div><div class="stack">${panel('资源状态',`<div class="panel-body scroll" style="max-height:480px">${table(['资源','位置','状态'],state.resources.map(r=>[esc(r.name),esc(node(r.node).name),badge(r.available_at>state.minute?'待增援':statusName(r.status),r.active?'':'good')]))}</div>`)}${panel('道路事件注入',`<div class="panel-body"><div class="field"><label>模拟道路中断</label><select id="road-select">${state.roads.filter(e=>!e.blocked).map(e=>`<option value="${e.id}">${e.id} · ${e.u}—${e.v}</option>`).join('')}</select></div><button id="block-road" class="primary">确认封路并重规划</button><p class="notice full">当前 ${state.metrics.blocked} 条阻断。道路变更、任务变更和计划快照同步持久化。</p></div>`)}</div></div>${panel('窗口内派遣清单',`<div class="panel-body">${table(['资源','任务','路线','出发','协同开始','结束','类型'],a.map(x=>[esc(x.resource),esc(x.name),x.path.join(' → '),x.depart,x.start,x.end,badge(x.provisional?'预测前置':'已发布模拟任务',x.provisional?'warn':'')]))}</div>`,state.plan.seconds?`${state.plan.status} · ${state.plan.seconds.toFixed(2)}s · ${state.plan.stability?.reassignments??0} 次改派 / ${state.plan.stability?.withdrawals??0} 次撤回`:'尚未规划','full')}`;mapRender('dispatch-map');gantt('gantt');$('#optimize').onclick=()=>action(async()=>{await api('optimize',{horizon:Number($('#horizon').value),stability:Number($('#stability').value),forecast:$('#preposition').checked,response_weight:state.settings.response_weight??10,objective_mode:state.settings.objective_mode||'weighted'});toast('滚动计划已生成并持久化')});$('#block-road').onclick=()=>action(async()=>{await api('roads/'+$('#road-select').value+'/block',{});toast('道路已阻断并完成重规划')})}
async function renderStrategy(){const clauses=await api('policies');$('#content').innerHTML=`<div class="layout"><div class="stack">${panel('当前灾情态势',`<div class="panel-body"><div class="notice warn">${state.forecast.level} · 指数 ${state.forecast.score.toFixed(2)}<br>待分配任务 ${state.metrics.pending} 项<br>可用资源 ${state.metrics.available} 项<br>道路中断 ${state.metrics.blocked} 条</div></div>`)}${panel('情景假设 / What-if',`<div class="panel-body"><div class="field"><label>额外封闭一条道路</label><select id="what-road"><option value="">无额外封路</option>${state.roads.filter(r=>!r.blocked).map(r=>`<option value="${r.id}">${r.id} ${r.u}—${r.v}</option>`).join('')}</select></div><label class="check"><input type="checkbox" id="what-add">增加一支搜救队</label><button id="what-run" class="primary">开始方案推演</button><p class="notice full">推演基于当前状态副本，不改变正在执行的仿真状态。</p></div>`)}</div><div class="stack">${panel('决策流程',`<div class="flow">${['当前态势','检索依据','确认任务','调度执行'].map((v,i)=>`<div><b>${i+1}</b><small>${v}</small></div>`).join('')}</div>`)}${panel('灾情理解与任务生成',`<div class="panel-body"><textarea id="event-text" placeholder="例如：N4 日地村模拟搜救区发现失联12人，受伤5人，需要搜救和医疗支援。">N4 日地村模拟搜救区发现失联12人，受伤5人，需要搜救和医疗支援。</textarea><label class="check"><input type="checkbox" id="live-model" ${state.api.configured?'':'disabled'}>使用实时大模型 <span class="badge">${esc(state.api.model)}</span></label><button id="extract" class="primary">解析灾情并检索预案</button><div id="candidate"></div></div>`)}${panel('策略方案对比','<div class="panel-body"><div id="what-results" class="three-columns"><div class="empty">运行推演后显示真实求解结果</div></div></div>','不同预测与稳定性设置')}</div><div class="stack">${panel('法规依据与政策检索',`<div class="panel-body"><div class="toolbar"><input id="policy-query" placeholder="搜索搜救、转移、医疗…" style="width:100%"><button id="policy-search" class="ghost small">检索</button></div><div id="clauses">${policyCards(clauses)}</div></div>`,'混合检索')}${panel('模型接入状态',`<div class="panel-body"><div class="notice">${esc(state.api.mode)}<br>离线方法：TF-IDF + LSA 潜在向量融合；没有将其标为 BGE。<br>模型输出先校验再确认，数值调度交由优化器。</div></div>`)}</div></div>`;
$('#extract').onclick=async()=>{
 const b=$('#extract');b.disabled=true;
 try{
  pending=await api('extract',{text:$('#event-text').value,live:$('#live-model').checked});
  $('#candidate').innerHTML=`<p>${badge(pending.mode)}</p><pre>${esc(JSON.stringify(pending.candidate,null,2))}</pre><div class="field"><label>确认地点</label><select id="candidate-node"><option value="" ${pending.candidate.node===null?'selected':''}>请选择明确地点</option>${state.nodes.filter(n=>n.kind!=='road').map(n=>`<option value="${n.id}" ${n.id===pending.candidate.node?'selected':''}>${esc(n.name)}</option>`).join('')}</select></div><div class="toolbar">${[['rescue','搜救'],['medical','医疗'],['engineering','工程']].map(([k,v])=>`<label><input type="checkbox" data-need="${k}" ${pending.candidate.needs.includes(k)?'checked':''}>${v}</label>`).join('')}</div><div class="two-columns">${[['missing','失联'],['injured','受伤']].map(([k,v])=>`<div class="field"><label>${v}人数（未知留空）</label><input id="count-${k}" type="number" min="0" max="100000" value="${pending.candidate.casualties[k]??''}"></div>`).join('')}</div><p class="notice">确认后按搜救/医疗/工程模板生成协同任务；数量与40分钟期限为实验模板。道路变化以候选中的 road_blocked 编号为准。</p><button id="confirm-event" class="primary full">批准修改后的事件并生成计划</button><button id="reject-event" class="ghost full">拒绝候选并保留审计记录</button>`;
  $('#clauses').innerHTML=policyCards(pending.clauses);
  $('#reject-event').onclick=()=>action(async()=>{await api('reject',pending);pending=null;toast('候选已拒绝并记录；未生成任务')});
  $('#confirm-event').onclick=()=>action(async()=>{
   pending.candidate.node=$('#candidate-node').value;
   pending.candidate.needs=[...document.querySelectorAll('[data-need]:checked')].map(e=>e.dataset.need);
   for(const k of ['missing','injured']){const value=$('#count-'+k).value;pending.candidate.casualties[k]=value===''?null:Number(value)}
   await api('confirm',pending);pending=null;toast('事件、任务与计划已持久化');
  });
 }catch(e){toast(e.message)}finally{b.disabled=false}
};
$('#policy-search').onclick=async()=>{try{$('#clauses').innerHTML=policyCards(await api('policies?q='+encodeURIComponent($('#policy-query').value)))}catch(e){toast(e.message)}};
$('#what-run').onclick=async()=>{const b=$('#what-run');b.disabled=true;try{const r=await api('whatif',{blocked:$('#what-road').value||null,additional:$('#what-add').checked});$('#what-results').innerHTML=r.map(x=>`<div class="strategy"><h3>${x.name}</h3><dl><dt>窗口内任务</dt><dd>${x.scheduled} 项</dd></dl><dl><dt>平均计划到达</dt><dd>${x.mean_response??'—'} 分</dd></dl><dl><dt>改派 / 撤回</dt><dd>${x.plan.stability?.reassignments??0} / ${x.plan.stability?.withdrawals??0}</dd></dl><dl><dt>求解状态</dt><dd>${x.plan.status}</dd></dl><p class="notice">${x.plan.forecast_enabled?'启用预测前置':'不启用预测前置'}<br>稳定惩罚 ${x.plan.stability_weight}</p></div>`).join('')}catch(e){toast(e.message)}finally{b.disabled=false}}}
function policyCards(items){return items.map(c=>`<div class="policy"><strong>${esc(c.section)}</strong><p>${esc(c.text)}</p><a href="${esc(c.url)}" target="_blank" rel="noreferrer">${esc(c.title)} ↗</a><p>${esc(c.scope)}</p><span class="badge">${esc(c.id)}</span></div>`).join('')}
async function renderEvidence(){const c=await api('catalog');$('#content').insertAdjacentHTML('beforeend',panel('案例资料与来源档案',`<div class="panel-body"><p class="notice">这是研究背景资料库。晚于当前模拟时刻公开的通报不进入预测、任务或资源统计；模拟路网和队伍均独立构造。</p>${table(['来源','公开时间','类型','本地保存范围'],c.sources.map(s=>[`<a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)}</a>`,esc(s.published_at),esc(s.kind),esc(s.snapshot_status)]))}${table(['事实编号','事件时间','公开时间','人工整理摘要','原文依据'],c.facts.map(f=>[esc(f.id),esc(f.event_time||'未明确'),esc(f.published_at),esc(f.summary),esc(f.evidence_excerpt)]))}</div>`,'真实资料与模拟参数分开管理','full'))}
function renderGaps(){const gaps=state.plan.gaps||[];$('#content').insertAdjacentHTML('beforeend',panel('本轮任务缺口',`<div class="panel-body">${gaps.length?table(['未完整安排的任务','全部资源需求','可行资源不足','原因'],gaps.map(g=>[esc(g.name),Object.entries(g.requirements).map(([k,v])=>`${esc(state.resource_names[k])} ×${v}`).join(' / '),Object.entries(g.deficits).map(([k,v])=>`${esc(state.resource_names[k])} 缺${v}`).join(' / ')||'存在单项可行资源',esc(g.reason)])):'<p class="notice">本轮考虑的任务均有完整计划，或尚未运行优化。计划完成仍需推进执行。</p>'}</div>`,'窗口内可解释缺口','full'))}
async function renderReplay(){history=await api('history');$('#content').innerHTML=`<div class="toolbar"><label>历史状态快照</label><select id="history-select">${history.map(h=>`<option value="${h.revision}" ${h.revision===state.revision?'selected':''}>版本 ${h.revision} · 第 ${h.minute} 分钟</option>`).join('')}</select><button id="load-history" class="primary">读取历史快照</button><button id="live-state" class="ghost">返回最新态势</button><button id="export-state">导出当前状态 JSON</button><span class="badge">只读回放，不回滚执行状态</span></div><div class="two-columns">${mapPanel('replay-map','事件复盘 · 历史快照')}${panel('决策与执行时间线',`<div class="panel-body scroll" style="max-height:460px">${events(50)}</div>`,'SQLite记录')}</div>${panel('历史计划时间轴','<div class="gantt" id="replay-gantt"></div>','对应当前选中快照','full')}${panel('实验依据',`<div class="panel-body"><div class="notice">V1 已有标准场景＋20个种子的配对实验，保留于 results/metrics.csv。V2 预测对比使用按时间划分的数据，见风险预测页。策略推演提供当前状态的模型消融，不能将窗口内预计指标当作已完成的长期执行效果。</div></div>`,'区分预测计划与实际执行','full')}`;mapRender('replay-map');gantt('replay-gantt');$('#load-history').onclick=async()=>{try{state=await api('history/'+$('#history-select').value);await render();toast('正在查看历史版本 '+state.revision)}catch(e){toast(e.message)}};$('#live-state').onclick=refresh;$('#export-state').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`state-v${state.revision}.json`;a.click();URL.revokeObjectURL(a.href)}}
async function render(){maps.forEach(m=>m.remove());charts.forEach(c=>c.dispose());maps=[];charts=[];const p=pages.find(p=>p[0]===page);$('#page-title').textContent=p[3];$('#page-subtitle').textContent=p[4];$('#clock').textContent=state.time+' · 模拟时钟';$('#revision').textContent='数据版本 '+state.revision;$('#nav').innerHTML=pages.map(p=>`<button data-page="${p[0]}" class="${p[0]===page?'active':''}"><span class="icon">${p[1]}</span><span class="label">${p[2]}</span></button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));await ({overview:()=>{renderOverview();renderDecisionTrace()},data:async()=>{renderData();renderHealth();await renderEvidence();await renderEnvironmentControls()},prediction:async()=>{await renderPrediction();await renderMultistep()},dispatch:()=>{renderDispatch();renderGaps();renderRoutingControls();renderResponseControls();renderObjectiveMode();renderDecisionTrace()},strategy:async()=>{await renderStrategy();renderDecisionTrace();await renderIntake()},replay:async()=>{await renderReplay();await renderResearchResults();await renderCurrentResearch()}})[page]();if(page==='replay'){const b=document.createElement('button');b.id='reset-demo';b.textContent='重置演示（保留历史）';b.onclick=()=>action(async()=>{await api('reset',{});toast('已重置，历史快照保留')});$('#content .toolbar').append(b)}if(state.plan.degraded){const notice=document.createElement('div');notice.className='notice warn';notice.textContent='本轮求解状态 '+state.plan.status+'，已降级为经过约束检查的贪心方案。';$('#content').prepend(notice)}}
async function refresh(){state=await api('state');await render()}
async function navigate(p){page=p;location.hash=p;window.scrollTo(0,0);try{await refresh()}catch(e){toast(e.message)}}
$('#advance').onclick=()=>action(async()=>{await api('advance',{minutes:10});toast('已推进10分钟，监测、任务和计划同步更新')});
$('#model-btn').onclick=()=>{$('#modal-content').innerHTML='<h3>本机大模型接入</h3><p>项目根目录.env会自动读取，支持DISASTER_API_KEY或DEEPSEEK_API_KEY，也兼容仅一行密钥。已有进程环境变量优先；密钥不进入浏览器或数据库。</p><pre>$env:DISASTER_API_KEY = "本机填写密钥"\n$env:DISASTER_BASE_URL = "https://api.deepseek.com"\n$env:DISASTER_MODEL = "deepseek-v4-flash"</pre><p>兼容 Chat Completions JSON 接口。配置后在策略决策页“多阶段灾情理解”支持实时调用、校验失败回退和逐项人工确认。</p>';$('#modal').showModal()};
window.addEventListener('resize',()=>{charts.forEach(c=>c.resize());maps.forEach(m=>m.invalidateSize())});
page=pages.some(p=>p[0]===location.hash.slice(1))?location.hash.slice(1):'overview';refresh().catch(e=>{$('#content').innerHTML='<div class="empty">服务连接失败：'+esc(e.message)+'<br>请启动 python -m uvicorn disaster.v2.api:app --port 8800</div>'});
