/* Operational workspace. Research diagnostics are not loaded by this application. */
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages=[['overview','home','总览','应急总控台','掌握灾情变化，统筹救援行动'],['data','data','监测数据','监测数据与来源','关注监测状态，核实现场信息'],['prediction','pulse','风险研判','风险趋势与研判','结合近期观测，提前关注重点区域'],['dispatch','truck','资源调度','救援资源与任务安排','查看任务、通行条件和资源去向'],['strategy','strategy','灾情处置','灾情报告与处置','核对报告、确认需求、查看行动依据'],['replay','clock','处置记录','处置记录与回顾','回顾已确认报告和任务安排变化']];
let state,page='overview',maps=[],charts=[],pending=null,readOnly=false,navigating=false,queuedPage=null;
const eventNames={disaster_report:'灾情报告',casualty_update:'新增伤亡',information_correction:'信息修正',road_closure:'道路中断',resource_failure:'资源故障',reinforcement:'增援到达',risk_change:'风险变化',secondary_risk:'次生风险',sensor_delay:'监测延迟',recovery:'恢复安置',uncertain_report:'待核实信息'};
const needNames={rescue:'人员搜救',medical:'医疗支援',engineering:'道路保障',supply:'物资安置'};
async function api(url,body){const r=await fetch('/api/workspace/'+url,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await r.json()}catch{throw Error('服务暂时不可用，请稍后重试')}if(!r.ok)throw Error(data.detail||'操作未完成，请稍后重试');return data}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',5000)}
async function action(fn){const controls=[...document.querySelectorAll('button')];controls.forEach(b=>b.disabled=true);try{await fn();await refresh()}catch(e){toast(e instanceof TypeError?'页面暂时无法更新，请刷新后重试':e.message)}finally{controls.forEach(b=>b.disabled=false)}}
function panel(title,body,extra='',cls=''){return `<section class="panel ${cls}"><div class="panel-title"><span>${title}</span><small>${extra}</small></div>${body}</section>`}
function table(headers,rows){return `<div class="wide-table"><table class="rows"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function badge(text,type=''){return `<span class="badge ${type}">${esc(text)}</span>`}
function node(id){return state.nodes.find(n=>n.id===id)||{name:'地点待核实',lat:30.08,lon:102.18}}
function resource(id){return state.resources.find(r=>r.id===id)?.name||'救援资源'}
function roadName(id){const r=state.roads.find(r=>r.id===id);return r?node(r.u).name+' — '+node(r.v).name:'路段待核实'}
function timeAt(minute){if(minute===null||minute===undefined)return '待安排';const m=9*60+Number(minute);return String(Math.floor(m/60)%24).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function statusName(s){return ({pending:'待安排',committed:'执行中',completed:'已完成',idle:'待命',travel:'行进中',working:'作业中',reserved:'协同待命',failed:'暂不可用'})[s]||'待核实'}
function publicText(text){let value=String(text||'');for(const r of state.resources)value=value.replaceAll(r.id,r.name);for(const r of state.roads)value=value.replaceAll(r.id,roadName(r.id));for(const n of [...state.nodes].sort((a,b)=>b.id.length-a.id.length))value=value.replace(new RegExp(n.id+'(?![0-9])','g'),n.name);return value.replaceAll('模拟','演练')}
function metric(name,value,unit,sub,kind,color=''){return `<div class="metric"><div class="symbol ${color}">${icon(kind)}</div><div><label>${name}</label><strong class="${color}">${value}</strong> <em>${unit}</em><small>${sub}</small></div></div>`}
function cards(){const m=state.metrics;return `<div class="cards">${metric('累计降雨',m.rainfall,'mm','过去24小时','rain')}${metric('区域风险',state.forecast.level,'','持续关注变化','alert','orange')}${metric('失联报告',m.missing,'人','按已核实报告统计','heart','red')}${metric('待命资源',m.available,'项','共 '+m.total+' 项资源','people')}${metric('待安排任务',m.pending,'项','优先处置紧急需求','layers')}${metric('道路中断',m.blocked,'处','共 '+m.roads+' 条工作路段','road',m.blocked?'red':'green')}</div>`}
function displayAssignments(){const active=state.resources.flatMap(r=>r.active?[r.active]:[]),keys=new Set(active.map(a=>a.resource+'/'+a.task+'/'+a.depart));return [...active,...state.plan.assignments.filter(a=>a.end>state.minute&&!keys.has(a.resource+'/'+a.task+'/'+a.depart))]}
function tasks(limit=8){return [...state.tasks].sort((a,b)=>a.priority-b.priority).slice(0,limit).map(t=>`<div class="task"><span class="priority p${t.priority}">${t.priority===1?'紧急':'一般'}</span><div><strong>${esc(t.name)}</strong><p>${esc(node(t.node).name)} · 期望 ${timeAt(t.deadline)} 前</p><p>${Object.entries(t.requirements).map(([k,v])=>esc(state.resource_names[k])+' ×'+v).join(' · ')}</p></div>${badge(statusName(t.status),t.status==='completed'?'good':t.status==='pending'?'warn':'')}</div>`).join('')||'<div class="empty">暂无待处置任务</div>'}
function timeline(){return [...state.timeline].reverse().slice(0,10).map(e=>`<div class="timeline-item"><time>${e.time}</time><span class="dot"></span><p>${esc(e.message)}</p></div>`).join('')||'<div class="empty">暂无处置记录</div>'}
function mapPanel(id='main-map',title='救援态势地图'){return `<section class="panel"><div id="${id}" class="map"><div class="map-title">${title}<small>全国区位 · 康定工作区域</small></div><div class="map-tools"><button data-view="country">全国总览</button><button data-view="local">康定现场</button><button data-base="local" class="selected">简洁地图</button><button data-base="online">街道地图</button><button data-layer="risk" class="selected" aria-pressed="true">风险</button><button data-layer="resources" class="selected" aria-pressed="true">资源</button><button data-fit aria-label="定位当前区域" title="定位当前区域">${icon('target')}</button></div><div class="map-legend"><span class="legend-mark risk"></span>重点关注区域<br><span class="legend-mark"></span>通行路段<br><span class="legend-mark blocked"></span>阻断路段<br><span class="legend-mark route"></span>救援路线</div></div><div class="map-note"><span class="map-status">可查看全国区位与康定现场</span><span>地图来源：DataV / © OpenStreetMap</span></div></section>`}
function chart(id,options){const el=$('#'+id);if(!el)return;const c=echarts.init(el,null,{renderer:'canvas'});charts.push(c);c.setOption({animationDuration:200,animation:!matchMedia('(prefers-reduced-motion: reduce)').matches,textStyle:{fontFamily:'Microsoft YaHei',color:'#71849b'},grid:{left:45,right:18,top:25,bottom:30},tooltip:{trigger:'axis'},...options});return c}
function line(id,history,forecast=[],unit=''){const values=[...history,...forecast];chart(id,{legend:{top:0,textStyle:{fontSize:10}},grid:{left:45,right:15,top:40,bottom:30},xAxis:{type:'category',boundaryGap:false,data:values.map(p=>timeAt(p.minute)),axisLabel:{fontSize:9}},yAxis:{type:'value',name:unit,splitLine:{lineStyle:{color:'#edf2f7'}}},series:[{name:'观测',type:'line',data:[...history.map(r=>r.value),...forecast.map(()=>null)],symbol:'none',itemStyle:{color:'#2089ff'},areaStyle:{opacity:.12}},{name:'趋势预估',type:'line',data:[...history.map(()=>null),...forecast.map(r=>r.value)],symbol:'none',lineStyle:{type:'dashed'},itemStyle:{color:'#efaa37'}}]})}
function utilization(){return Object.entries(state.resource_names).map(([kind,name])=>{const all=state.resources.filter(r=>r.type===kind),busy=all.filter(r=>r.active).length;return `<div class="progress-row"><span>${esc(name)}</span><span class="bar"><i style="width:${all.length?busy/all.length*100:0}%"></i></span><span>${busy} / ${all.length}</span></div>`}).join('')}
function changes(){const c=state.changes_summary;return panel('任务安排变化',`<div class="panel-body"><div class="notice">新增安排 ${c.new} 项 · 调整资源 ${c.reassigned} 项 · 撤回安排 ${c.withdrawn} 项</div>${state.changes.length?table(['救援资源','任务','原预计到达','现预计到达'],state.changes.map(r=>[esc(r.resource),esc(r.task),r.before,r.after])):'<p class="notice">当前没有同一任务的预计到达时间变更。</p>'}<p>未完成的需求保留在任务清单中，已出发资源继续跟踪执行。</p></div>`,'以当前安排为准','full')}
function overview(){const f=state.forecast;$('#content').innerHTML=cards()+`<div class="layout"><div class="stack">${panel('监测摘要',`<div class="panel-body">${table(['指标','当前观测'],Object.entries(f.series).map(([k,v])=>[state.sensor_types[k]?.label,Number(v.history.at(-1)?.value??0).toFixed(1)+' '+v.unit]))}<p class="notice">当前为${state.environment}，请结合现场信息核实。</p></div>`)}${panel('处置动态',`<div class="panel-body">${timeline()}</div>`)}</div><div>${mapPanel()}<div class="bottom-grid">${panel('降雨趋势','<div class="chart" id="rain"></div>')}${panel('资源使用',`<div class="panel-body">${utilization()}</div>`)}${panel('关注区域',`<div class="panel-body">${f.zones.map(z=>`<div class="progress-row"><span>${esc(node(z.node).name)}</span><span class="bar"><i style="width:${z.score*100}%"></i></span><span>${z.score>=.7?'高':'中'}</span></div>`).join('')}</div>`)}</div></div><div class="stack">${panel('当前任务',`<div class="panel-body">${tasks(5)}</div>`)}${panel('行动提醒',`<div class="panel-body"><div class="notice warn">${state.metrics.pending} 项任务待安排，${state.metrics.blocked} 处路段中断。请先核实紧急需求，再组织支援。</div><button class="primary full" data-goto="dispatch">查看救援安排 →</button></div>`)}</div></div>`;cartographicMap('main-map');line('rain',f.series.rainfall.history,[],'mm/h')}
function monitoring(){const rows=state.observations;$('#content').innerHTML=cards()+`<div class="layout"><div class="stack">${panel('监测指标',`<div class="panel-body">${Object.entries(state.sensor_types).map(([k,v])=>`<div class="check">${icon('pulse')} ${v.label} <span class="badge">${v.unit}</span></div>`).join('')}<p class="notice">演练观测与历史资料分别使用，页面时间为当前回放时刻。</p></div>`)}</div><div>${mapPanel('data-map','监测区域与救援现场')}</div><div class="stack">${panel('监测状态',`<div class="panel-body">${table(['数据流','状态'],state.health.map(r=>[esc(r.name),badge(r.status,r.status==='正常'?'good':'warn')]))}</div>`)}</div></div>${panel('近期观测记录',`<div class="panel-body"><button class="ghost small" id="export-observations">导出观测表</button><div class="scroll">${table(['时间','监测点','指标','数值','单位'],[...rows].reverse().map(r=>[timeAt(r.minute),'监测点 '+esc(r.station_id.slice(-1)),state.sensor_types[r.type]?.label,r.value,esc(r.unit)]))}</div></div>`,'当前可见记录','full')}`;cartographicMap('data-map');$('#export-observations').onclick=()=>downloadCsv('观测记录.csv',[['时间','监测点','指标','数值','单位'],...rows.map(r=>[timeAt(r.minute),'监测点 '+r.station_id.slice(-1),state.sensor_types[r.type]?.label,r.value,r.unit])])}
function prediction(){const f=state.forecast;$('#content').innerHTML=cards()+`<p class="notice ${f.eligible_for_decision?'':'warn'}">${f.eligible_for_decision?'观测可用于趋势研判。':'部分监测数据已过期，暂停据此提前部署资源。'}风险等级用于提示关注顺序，不代表灾害发生概率。</p><div class="layout"><div class="stack">${Object.entries(f.series).map(([k,v])=>panel(state.sensor_types[k]?.label,`<div id="trend-${k}" class="chart"></div>`,v.unit)).join('')}</div><div>${mapPanel('risk-map','重点关注区域')}${panel('未来风险趋势','<div id="risk-trend" class="chart large"></div>','关注强度','full')}</div><div class="stack">${panel('区域研判',`<div class="panel-body">${f.zones.map(z=>`<div class="task"><span class="priority ${z.score>=.7?'':'p2'}">${z.score>=.7?'高':'中'}</span><div><strong>${esc(node(z.node).name)}</strong><p>请关注降雨变化与现场通行情况</p></div></div>`).join('')}</div>`)}${panel('处置建议',`<div class="panel-body"><div class="notice">保持现场联络，核实新增人员需求。道路、监测或任务发生变化后，及时复核救援安排。</div><button class="primary full" data-goto="strategy">登记现场报告</button></div>`)}</div></div>`;cartographicMap('risk-map',true);for(const [k,v] of Object.entries(f.series))line('trend-'+k,v.history.slice(-18),v.forecast,v.unit);line('risk-trend',[],f.risk.map(r=>({minute:r.minute,value:r.score})),'关注强度')}
function gantt(){const a=displayAssignments();if(!a.length){$('#gantt').innerHTML='<div class="empty">安排任务后显示执行时间轴</div>';return}const names=[...new Set(a.map(r=>r.resource))];chart('gantt',{grid:{left:90,right:22,top:25,bottom:35},tooltip:{formatter:p=>`${esc(resource(p.data.raw.resource))} → ${esc(publicText(p.data.raw.name))}<br>出发 ${timeAt(p.data.raw.depart)} · 到达 ${timeAt(p.data.raw.arrival)} · 结束 ${timeAt(p.data.raw.end)}`},xAxis:{type:'value',min:state.minute,axisLabel:{formatter:timeAt,fontSize:10}},yAxis:{type:'category',data:names.map(resource),axisLabel:{fontSize:10}},series:[{type:'custom',renderItem:(params,api)=>{const start=api.coord([api.value(1),api.value(0)]),end=api.coord([api.value(2),api.value(0)]);return {type:'rect',shape:{x:start[0],y:start[1]-5,width:Math.max(1,end[0]-start[0]),height:10,r:3},style:api.style()}},encode:{x:[1,2],y:0},data:a.flatMap(r=>[{value:[names.indexOf(r.resource),r.depart,r.arrival],raw:r,itemStyle:{color:'#f2b54f'}},{value:[names.indexOf(r.resource),r.start,r.end],raw:r,itemStyle:{color:'#4095fa'}}]).filter(r=>r.value[2]>r.value[1])}]})}
function dispatch(){const a=displayAssignments();$('#content').innerHTML=cards()+`<div class="layout"><div class="stack">${panel('任务清单',`<div class="panel-body scroll" style="max-height:500px">${tasks(30)}</div>`)}${panel('安排救援',`<div class="panel-body"><div class="field"><label for="preference">处置侧重</label><select id="preference"><option value="balanced">兼顾紧急需求与整体响应</option><option value="urgent">优先满足紧急需求</option></select></div><button class="primary" id="dispatch-action">更新救援安排</button><p class="notice">已出发和正在作业的资源保留执行承诺。</p></div>`)}</div><div>${mapPanel('dispatch-map','救援路线与任务分布')}${panel('任务执行时间轴','<div id="gantt" class="gantt"></div>','橙色：行程 · 蓝色：作业','full')}</div><div class="stack">${panel('救援资源',`<div class="panel-body scroll" style="max-height:475px">${table(['名称','位置','状态'],state.resources.map(r=>[esc(r.name),esc(node(r.node).name),badge(r.available_at>state.minute?'尚未到达':statusName(r.status),r.status==='failed'?'danger':r.active?'':'good')]))}</div>`)}${panel('通行情况更新',`<div class="panel-body"><div class="field"><label for="blocked-road">选择中断路段</label><select id="blocked-road">${state.roads.filter(r=>!r.blocked).map(r=>`<option value="${r.id}">${esc(roadName(r.id))}</option>`).join('')}</select></div><button id="road-action" class="primary">确认道路中断</button></div>`)}</div></div>${panel('派遣安排',`<div class="panel-body"><p class="notice">${esc(state.plan.message)}</p>${table(['资源','任务','前往地点','预计到达','协同开始','结束'],a.map(r=>[esc(resource(r.resource)),esc(publicText(r.name)),esc(node(r.node).name),timeAt(r.arrival),timeAt(r.start),timeAt(r.end)]))}</div>`,'计划时间供行动复核','full')}${panel('尚需支援',`<div class="panel-body">${state.plan.gaps.length?table(['任务','资源需求','处置提示'],state.plan.gaps.map(g=>[esc(g.name),Object.entries(g.requirements).map(([k,v])=>esc(state.resource_names[k])+' ×'+v).join(' / '),esc(g.reason)])):'<p class="notice">当前没有报告资源缺口，请继续跟踪执行情况。</p>'}</div>`,'未满足需求不会自动忽略','full')}${changes()}`;cartographicMap('dispatch-map');gantt();$('#dispatch-action').onclick=()=>action(async()=>{await api('dispatch',{preference:$('#preference').value});toast('救援安排已更新')});$('#road-action').onclick=()=>action(()=>api('road',{road:$('#blocked-road').value}))}
function policyCards(rows){return rows.map(r=>`<div class="policy"><strong>${esc(r.section)}</strong><p>${esc(r.text)}</p><a href="${esc(r.url)}" target="_blank" rel="noreferrer">${esc(r.title)} ↗</a></div>`).join('')}
async function strategy(){const [stages,clauses]=await Promise.all([api('stages'),api('policies')]);$('#content').innerHTML=`<div class="layout"><div class="stack">${panel('现场报告',`<div class="panel-body"><div class="field"><label for="report-location">报告地点</label><select id="report-location"><option value="">地点待核实 / 多个地点</option>${state.nodes.map(n=>`<option value="${n.id}">${esc(n.name)}</option>`).join('')}</select></div><label for="report-text">报告内容</label><textarea id="report-text" placeholder="描述当前情况、人员需求和通行变化…"></textarea><button id="recognize" class="primary full">整理报告并核对</button><p class="notice">请以核实后的现场信息为准，整理结果需逐项确认。</p></div>`)}${panel('当前处置情况',`<div class="panel-body"><p>失联报告 ${state.metrics.missing} 人</p><p>待安排任务 ${state.metrics.pending} 项</p><p>道路中断 ${state.metrics.blocked} 处</p><button class="ghost" data-goto="dispatch">查看任务安排 →</button></div>`)}</div><div class="stack">${panel('报告审核',`<div class="panel-body" id="review"><div class="empty">录入现场报告或准备演练阶段后，在这里核对地点、人数和需求。</div></div>`)}${panel('阶段演练',`<div class="panel-body"><ol class="stage-track">${stages.map((s,i)=>`<li class="${i<(state.scenario_cursor??0)?'done':i===(state.scenario_cursor??0)?'current':''}"><strong>${timeAt(s.minute)}</strong>${esc(s.title)}</li>`).join('')}</ol><p class="notice">阶段中的人数、封路、资源故障和增援为演练设定。准备下一阶段会推进演练时间，核对后再确认当前报告。</p><div class="toolbar"><button id="start-exercise">重新开始演练</button><button id="prepare-stage" class="primary" ${state.scenario_cursor===undefined||state.scenario_cursor>=9?'disabled':''}>准备下一阶段</button></div></div>`)}${panel('行动说明',`<div class="panel-body"><button id="explain-action" class="ghost">生成当前行动说明</button><div id="explanation"></div></div>`)}</div><div class="stack">${panel('相关预案依据',`<div class="panel-body"><div class="toolbar"><input id="policy-query" aria-label="检索预案" placeholder="搜救、医疗、安置…"><button id="search-policy">检索</button></div><div id="policies" class="scroll" style="max-height:700px">${policyCards(clauses)}</div></div>`)}</div></div>`;
 $('#recognize').onclick=()=>action(async()=>{pending=await api('extract',{text:$('#report-text').value,location:$('#report-location').value||null})});
 $('#start-exercise').onclick=()=>confirmDialog('重新开始阶段演练？','当前演练进度将重置，已有处置记录保留。',()=>action(async()=>{await api('start',{});pending=null}));
 $('#prepare-stage').onclick=()=>action(async()=>{pending=await api('prepare',{})});
 $('#search-policy').onclick=async()=>{try{$('#policies').innerHTML=policyCards(await api('policies?q='+encodeURIComponent($('#policy-query').value)))}catch(e){toast(e instanceof TypeError?'页面暂时无法更新，请刷新后重试':e.message)}};
 $('#explain-action').onclick=async()=>{const b=$('#explain-action');b.disabled=true;try{const r=await api('explain',{});$('#explanation').innerHTML=r.statements.map(t=>`<p>${esc(t)}</p>`).join('')+r.citations.map(c=>`<blockquote>${esc(c.text)}</blockquote>`).join('')+`<p class="notice">${esc(r.notice)}</p>`}catch(e){toast(e instanceof TypeError?'页面暂时无法更新，请刷新后重试':e.message)}finally{b.disabled=false}};
 if(pending)showReview();
}
function options(items,selected){return items.map(([id,name])=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(name)}</option>`).join('')}
function showReview(){
 $('#review').innerHTML=`<p>${badge(pending.recognition)}</p><blockquote class="notice">${esc(publicText(pending.text))}</blockquote>${pending.events.map((e,i)=>`<fieldset class="review-form" data-event="${i}"><legend>报告 ${i+1}</legend><div class="two-columns"><div class="field"><label>事项类别<select data-field="event_type">${options(Object.entries(eventNames),e.event_type)}</select></label></div><div class="field"><label>发生地点<select data-field="node">${options([['','地点待核实'],...state.nodes.map(n=>[n.id,n.name])],e.node||'')}</select></label></div><div class="field"><label>失联人数<input data-field="missing" type="number" min="0" max="100000" value="${e.missing??''}" placeholder="未知留空"></label></div><div class="field"><label>受伤人数<input data-field="injured" type="number" min="0" max="100000" value="${e.injured??''}" placeholder="未知留空"></label></div><div class="field"><label>人数口径<select data-field="count_mode">${options([['absolute','当前核实总数'],['delta','本次新增加人数']],e.count_mode)}</select></label></div><div class="field"><label>风险程度<select data-field="risk_level">${options([['','未评定'],['low','低'],['medium','中'],['high','高']],e.risk_level||'')}</select></label></div></div><label>所需支援</label><div class="toolbar">${Object.entries(needNames).map(([k,v])=>`<label><input type="checkbox" data-need="${k}" ${e.needs.includes(k)?'checked':''}>${v}</label>`).join('')}</div><details ${e.road_ids.length||e.resource_ids.length||e.station_ids.length?'open':''}><summary>关联道路、资源与监测点</summary>${[['road_ids','道路',state.roads.map(r=>[r.id,roadName(r.id)])],['resource_ids','救援资源',state.resources.map(r=>[r.id,r.name])],['station_ids','监测点',['S01','S02','S03'].map((s,j)=>[s,'监测点 '+(j+1)])]].map(([k,title,items])=>`<div class="field"><label>${title}<select data-field="${k}" multiple size="3">${items.map(([id,name])=>`<option value="${id}" ${e[k].includes(id)?'selected':''}>${esc(name)}</option>`).join('')}</select></label></div>`).join('')}</details><p class="review-evidence">原文依据：${esc(publicText(e.evidence))}</p></fieldset>`).join('')}<div class="toolbar"><button id="confirm-report" class="primary">核实并确认报告</button><button id="reject-report">退回待核实</button></div><p class="notice">未知人数请留空；信息修正覆盖原统计，不重复累加。</p>`;
 $('#confirm-report').onclick=()=>action(async()=>{const events=pending.events.map((e,i)=>{const form=$(`[data-event="${i}"]`),r={...e};for(const k of ['event_type','node','count_mode','risk_level'])r[k]=form.querySelector(`[data-field="${k}"]`).value||null;for(const k of ['missing','injured']){const v=form.querySelector(`[data-field="${k}"]`).value;r[k]=v===''?null:Number(v)}for(const k of ['road_ids','resource_ids','station_ids'])r[k]=[...form.querySelector(`[data-field="${k}"]`).selectedOptions].map(o=>o.value);r.needs=[...form.querySelectorAll('[data-need]:checked')].map(c=>c.dataset.need);return r});await api('confirm',{token:pending.token,events});pending=null;toast('报告已确认，任务安排已更新')});
 $('#reject-report').onclick=()=>action(async()=>{await api('reject',{token:pending.token});pending=null;toast('已退回待核实报告')});
}
async function replay(){const history=await api('history');$('#content').innerHTML=`<div class="toolbar"><label for="history-record">处置时点</label><select id="history-record">${history.map((h,i)=>`<option value="${h.id}">${h.time} · ${i===0?'最近一次':'记录 '+(history.length-i)}</option>`).join('')}</select><button id="load-record">查看此时点</button><button id="return-now" class="primary">返回当前态势</button></div>${readOnly?'<p class="notice warn">正在查看历史记录，此页仅供回顾。</p>':''}<div class="two-columns">${mapPanel('replay-map','历史处置区域')}${panel('处置动态',`<div class="panel-body">${timeline()}</div>`)}</div>${panel('人员报告核实记录',`<div class="panel-body">${state.reports.length?table(['核实时间','地点','失联人数','受伤人数'],state.reports.map(r=>[r.time,esc(r.location),r.missing??'待核实',r.injured??'待核实'])):'<div class="empty">暂无已核实人员报告</div>'}</div>`,'每次修正保留原记录','full')}${changes()}`;cartographicMap('replay-map');$('#load-record').onclick=async()=>{try{state=await api('history/'+$('#history-record').value);readOnly=true;await render()}catch(e){toast(e instanceof TypeError?'页面暂时无法更新，请刷新后重试':e.message)}};$('#return-now').onclick=refresh}
function downloadCsv(name,rows){const text='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function confirmDialog(title,text,fn){$('#modal-content').innerHTML=`<h3>${title}</h3><p>${text}</p><button id="modal-confirm" class="primary">确认</button>`;$('#modal').showModal();$('#modal-confirm').onclick=()=>{$('#modal').close();fn()}}
async function render(){maps.forEach(m=>m.remove());charts.forEach(c=>c.dispose());maps=[];charts=[];const p=pages.find(p=>p[0]===page);$('#page-title').textContent=p[3];$('#page-subtitle').textContent=p[4];$('#clock').textContent=state.time;$('#nav').innerHTML=pages.map(p=>`<button data-page="${p[0]}" class="${p[0]===page?'active':''}" aria-label="${p[2]}" aria-current="${p[0]===page?'page':'false'}"><span class="icon">${icon(p[1])}</span><span class="label">${p[2]}</span></button>`).join('');$('#session-status').innerHTML=`<span class="status-dot"></span>${esc(state.environment)}<span class="session-separator"></span>康定工作区域<span class="session-separator"></span>${readOnly?'历史记录，只读查看':'数据含演练设定，请以核实信息为准'}`;await ({overview,data:monitoring,prediction,dispatch,strategy,replay})[page]();document.querySelectorAll('#nav [data-page],[data-goto]').forEach(b=>b.onclick=()=>navigate(b.dataset.page||b.dataset.goto));$('#advance').disabled=readOnly;document.body.dataset.page=page;requestAnimationFrame(()=>{charts.forEach(c=>{if(!c.isDisposed()&&c.getDom().clientWidth)c.resize()});maps.forEach(m=>m.invalidateSize())})}
async function refresh(){state=await api('state');readOnly=false;await render()}
async function navigate(name){if(navigating){queuedPage=name;return}navigating=true;try{do{page=queuedPage||name;queuedPage=null;location.hash=page;window.scrollTo(0,0);await refresh()}while(queuedPage)}catch(e){toast(e instanceof TypeError?'页面暂时无法更新，请刷新后重试':e.message)}finally{navigating=false}}
$('#advance').onclick=()=>action(()=>api('advance',{minutes:10}));
$('#help-btn').onclick=()=>{$('#modal-content').innerHTML='<h3>工作台使用说明</h3><p>通过全国总览定位康定工作区域；在灾情处置页核实报告后，查看救援安排和通行变化。</p><p>当前展示包含演练数据，阶段人数、道路变化和救援资源不代表真实救援记录。预计到达时间供复核参考。</p><p>如需调整接入服务或数据来源，请联系维护人员。</p>';$('#modal').showModal()};
window.addEventListener('resize',()=>{charts.forEach(c=>{if(!c.isDisposed()&&c.getDom().clientWidth)c.resize()});maps.forEach(m=>m.invalidateSize())});
page=pages.some(p=>p[0]===location.hash.slice(1))?location.hash.slice(1):'overview';refresh().catch(()=>$('#content').innerHTML='<div class="empty">暂时无法连接工作台，请稍后刷新或联系维护人员。</div>');
