function renderDecisionTrace(){
 const trace=state.decision_traces?.at(-1);
 const html=trace?`<div class="trace-flow"><div><small>1 · 已接收数据</small>${Object.entries(trace.observations).map(([k,v])=>`<p>${esc(state.sensor_types[k].label)} ${Number(v.value).toFixed(2)} ${esc(v.unit)}<br><small>观测第 ${v.minute} 分钟</small></p>`).join('')}</div><div><small>2 · 联合预测 / 区域排序</small><h3>${trace.risk_before===null?'—':Number(trace.risk_before).toFixed(2)} → ${Number(trace.risk_after).toFixed(2)}</h3>${trace.zones.map(z=>`<p>${esc(z.node)} · ${Number(z.score).toFixed(2)}</p>`).join('')}<small>风险排序，不是灾害概率</small></div><div><small>3 · 触发与约束求解</small><p>${esc(trace.triggers.join('；'))}</p><h3>${esc(trace.status)} · ${(trace.replan_latency_seconds*1000).toFixed(0)} ms</h3><p>U ${trace.objective_terms.unmet??'—'} · R ${trace.objective_terms.response??'—'}<br>L ${trace.objective_terms.lateness??'—'} · T ${trace.objective_terms.travel??'—'}</p></div><div><small>4 · 方案变化</small>${trace.added.slice(0,5).map(a=>`<p>${esc(a.resource)} → ${esc(a.node)}<br><small>${esc(a.task)} · 第${a.arrival}分钟到达</small></p>`).join('')||'<p>无新增分配</p>'}<p>改派 ${trace.stability.reassignments??0} · 撤回 ${trace.stability.withdrawals??0}</p></div></div><details><summary>查看计划到达变化与完整证据</summary><p class="notice">不同轮次的任务、时刻和约束可能变化，不直接相减目标值。到达时间变化是计划估计，不是已经实现的救援收益。前置仅使用当前任务窗口中完全未占用的剩余资源。</p><pre>${esc(JSON.stringify(trace,null,2))}</pre></details>`:'<div class="empty">运行一次优化或注入事件后，显示数据 → 预测 → 触发 → 分配的可核验记录。</div>';
 $('#content').insertAdjacentHTML(page==='dispatch'?'beforeend':'afterbegin',panel('决策追踪 · 为什么方案变化',`<div class="panel-body">${html}</div>`,'当前版本 '+state.revision,'full'));
}
async function renderEnvironmentControls(){
 const info=await api('environment'),historical=state.environment_mode==='historical';
 $('#content').insertAdjacentHTML('afterbegin',panel('研究数据与预测模式',`<div class="panel-body"><div class="toolbar"><label>环境数据</label><select id="environment-mode"><option value="synthetic" ${!historical?'selected':''}>模拟 · 三站四变量 · 5分钟</option><option value="historical" ${historical?'selected':''}>GPM＋ERA5-Land · 三点两变量 · 小时</option></select><label>风险排序</label><select id="risk-mode"><option value="rule" ${state.risk_mode!=='empirical'?'selected':''}>规则归一化</option><option value="empirical" ${state.risk_mode==='empirical'?'selected':''}>训练历史经验分位</option></select><button id="apply-environment" class="primary">应用并重置回放</button></div><p class="notice">${historical?'历史最终产品/再分析的事后研究回放，不代表2024年当时可获得的数据；不混入模拟水位和位移。':'三个模拟站点的四变量联合构造滞后特征，保持可控基线。'}<br>Bronze：原始响应与SHA-256 → Silver：${info.native_rows}条原生观测 → Gold：${info.hourly_rows}条小时联合输入。历史数据没有插值成5分钟，小时尺度误差单独报告。</p><details><summary>来源、原生频率与处理说明</summary><p>NASA GES DISC IMERG Final V07：半小时降雨率；ERA5-Land via Open-Meteo：每小时0—7cm土壤体积含水率。取2024-07-20至2024-08-05三个网格点。任务、资源和风险阈值仍为模拟设定。</p></details></div>`,'真实历史数据 ≠ 现场实时数据','full'));
 $('#apply-environment').onclick=()=>action(async()=>{await api('reset',{environment_mode:$('#environment-mode').value,risk_mode:$('#risk-mode').value});toast('已切换环境数据并重置回放，历史保留')});
}
function renderResponseControls(){
 $('#content').insertAdjacentHTML('beforeend',panel('目标函数对照',`<div class="panel-body"><p>J = U + β R + 10 L + T + λ C；R = Σ w(priority) × (开始时间 − 发布时间)，优先级权重 5 / 3 / 1。未满足任务的R为0，缺口由U计入。</p><div class="toolbar"><label>响应时间权重 β</label><input id="response-weight" type="number" min="0" max="100" value="${state.settings.response_weight??10}"><button id="apply-response" class="primary">更新目标并优化</button></div><p class="notice">β=0保留无响应惩罚对照；不预设β=10一定胜出。C只比较旧计划中仍待执行的承诺，首次分配和正常完成不计入。</p></div>`,'目标分项可在决策追踪中核对','full'));
 $('#apply-response').onclick=()=>action(()=>api('optimize',{...state.settings,response_weight:Number($('#response-weight').value)}));
}
async function renderResearchResults(){
 const data=await api('research');
 const mean=(rows,key)=>{const valid=rows.filter(r=>r[key]!==''&&r[key]!==null&&r[key]!==undefined);return valid.length?valid.reduce((s,r)=>s+Number(r[key]),0)/valid.length:null};
 const format=(value,digits=2)=>value===null?'—':Number(value).toFixed(digits);
 if(data.scheduling?.length){
  const methods=[...new Set(data.scheduling.map(r=>r.method))];
  $('#content').insertAdjacentHTML('beforeend',panel('B · 资源紧缺 × 事件强度',`<div class="panel-body"><div class="toolbar"><select id="result-scale">${['1','0.75','0.5','0.35'].map(s=>`<option value="${s}">资源比例 ${Number(s)*100}%</option>`).join('')}</select><select id="result-rate">${['low','medium','high'].map(s=>`<option>${s}</option>`).join('')}</select></div><div id="factorial-results"></div><p class="notice">共享输入、资源约束和执行器。响应仅统计已开始任务，必须同时看缺口。区域Gini只衡量已有开始记录的区域，未服务区域另行计数。</p></div>`,'各组合固定种子的均值','full'));
  const update=()=>{const subset=data.scheduling.filter(r=>Number(r.resource_scale)===Number($('#result-scale').value)&&r.event_rate===$('#result-rate').value);$('#factorial-results').innerHTML=table(['方法 / 种子数','P1完成率','平均响应','缺口单位','行程分钟','改派 / 撤回','区域Gini','未服务区域','违规'],methods.map(method=>{const rows=subset.filter(r=>r.method===method);return [esc(method)+' / '+rows.length,format(mean(rows,'urgent_satisfaction')*100,1)+'%',format(mean(rows,'mean_response')),format(mean(rows,'unmet')),format(mean(rows,'travel'),1),format(mean(rows,'reassignments'))+' / '+format(mean(rows,'withdrawals')),format(mean(rows,'region_gini'),3),format(mean(rows,'unserved_regions')),rows.reduce((a,r)=>a+Number(r.violations),0)]}))};
  $('#result-scale').onchange=update;$('#result-rate').onchange=update;update();
 }
 if(data.ablation?.length){
  const seeds=new Set(data.ablation.map(r=>r.seed));
  const compared=data.scheduling.filter(r=>r.method==='rolling'&&Number(r.resource_scale)===.5&&r.event_rate==='high'&&seeds.has(r.seed));
  $('#content').insertAdjacentHTML('beforeend',panel('响应目标消融 · 相同种子与输入',`<div class="panel-body">${table(['目标','配对种子','P1完成率','平均响应','缺口单位','区域Gini'],[['β = 0',data.ablation],['β = 10',compared]].map(([label,rows])=>[label,rows.length,format(mean(rows,'urgent_satisfaction')*100,1)+'%',format(mean(rows,'mean_response')),format(mean(rows,'unmet')),format(mean(rows,'region_gini'),3)]))}<p class="notice">固定50%资源 / 高事件强度；其余约束与参数相同。比较响应时同时看完成率与缺口，不预设增加响应项一定改善全部指标。</p></div>`,'仅改变响应时间权重','full'));
 }
 if(data.stress?.length)$('#content').insertAdjacentHTML('beforeend',panel('C · 端到端动态压力测试',`<div class="panel-body">${table(['情景','重规划延迟 ms','违规','计划改派','计划撤回','P1响应'],data.stress.map(r=>[esc(r.scenario),Number(r.latency_ms).toFixed(1),r.violations,r.reassignments,r.withdrawals,r.p1_response]))}</div>`,'道路 / P1 / 故障 / 延迟 / 增援 / 同时事件','full'));
 $('#content').insertAdjacentHTML('beforeend',panel('可复核实验文件',`<div class="panel-body toolbar">${['forecast_synthetic','forecast_historical','scheduling','ablation','stress'].map(name=>`<a href="/api/research/export/${name}">下载 ${name}.csv</a>`).join('')}</div>`,'A 预测 / B 调度 / C 系统压力','full'));
}
